convert windows-incompatible quotations
The original quotes cause the following issue on windows install:

PS C:\Git\MineDojo> pip install -e .
Obtaining file:///C:/Git/MineDojo
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [10 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "C:\Git\MineDojo\setup.py", line 38, in <module>
          long_description=_read_file("README.md"),
        File "C:\Git\MineDojo\setup.py", line 16, in _read_file
          return fp.read()
        File "C:\Users\flash\AppData\Local\Programs\Python\Python310\lib\encodings\cp1252.py", line 23, in decode
          return codecs.charmap_decode(input,self.errors,decoding_table)[0]
      UnicodeDecodeError: 'charmap' codec can't decode byte 0x9d in position 15627: character maps to <undefined>
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.